version: 0.2

env:
  variables:
    BUILD_PREFIX: "ahorro-ui/android"

phases:
  install:
    runtime-versions:
      docker: 20
    commands:
      - echo Installing Flutter...
      - git clone https://github.com/flutter/flutter.git -b stable --depth 1
      - export PATH="$PATH:`pwd`/flutter/bin"
      - flutter doctor

  build:
    commands:
      - |
        echo Setting up environment...
        export TIMESTAMP=$(date +%Y-%m-%d-%H%M)
        echo "Timestamp: $TIMESTAMP"

        flutter pub get

        echo Building Debug Android APK...
        flutter build apk --debug

        echo Building Release Android APK...
        flutter build apk --release

        echo Building Release Android App Bundle...
        flutter build appbundle --release

        echo Creating output directory...
        mkdir -p output/$BUILD_PREFIX/build-$TIMESTAMP

        echo Copying APKs and AABs to output directory...
        cp build/app/outputs/flutter-apk/app-debug.apk output/ahorro-debug-$TIMESTAMP.apk
        cp build/app/outputs/flutter-apk/app-release.apk output/ahorro-release-$TIMESTAMP.apk
        cp build/app/outputs/bundle/release/app-release.aab output/ahorro-release-$TIMESTAMP.aab

artifacts:
  files:
    - '**/*'
  discard-paths: no
  base-directory: output
